// must be identical with common.hw 

#define WORD_WIDTH 32
#define DECODER_MEM_ADDR_WIDTH 6
#define DECODER_MEM_DATA_WIDTH 8
#define DECODER_MEM_DATA_DEPTH 64
#define STACK_MEM_ADDR_WIDTH 8
#define STACK_MEM_DATA_WIDTH 32
#define STACK_STEP 4	// STACK_MEM_DATA_WIDTH in bytes
#define STACK_MEM_DATA_DEPTH 256
#define INSTR_WIDTH 16
#define FIFO_ITEM_WIDTH (DECODER_MEM_ADDR_WIDTH+INSTR_WIDTH)
